Web/Models/ErrorViewModel.cs
using System;

namespace Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web/Controllers/ConfigurationController.cs
using System.Threading.Tasks;
using Data.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Model;

namespace Web.Controllers
{
    public class ConfigurationController : Controller
    {
        private IConfigurationRepository _configurationRepository;

        public ConfigurationController(IConfigurationRepository configurationRepository, IConfiguration configuration)
        {
            this._configurationRepository = configurationRepository;
            _configurationRepository.ConnectionString = configuration.GetConnectionString("ConfDb");
        }

        public async Task<IActionResult> Index()
        {
            var list = await _configurationRepository.GetAllAsync();

            return View(list);
        }


        public IActionResult Error()
        {
            return NoContent();
        }

        public ViewResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<RedirectToActionResult> Insert(ConfigurationObject configurationObject)
        {
            await _configurationRepository.InsertAsync(configurationObject);

            return RedirectToAction("Success");
        }

        [HttpPost]
        public async Task<RedirectToActionResult> Update(ConfigurationObject configurationObject)
        {
            await _configurationRepository.UpdateAsync(configurationObject);

            return RedirectToAction("Success");
        }

        public IActionResult Success()
        {
            return View();
        }

        public IActionResult Edit(int id)
        {
            var model = _configurationRepository.FindById(id);

            return View(model);
        }
    }
}

Web/Views/Configuration/Create.cshtml
@model Model.ConfigurationObject

<html>
<head>
    <title>Ekle</title>
</head>
<body>

    <p>Yeni Configurasyon Kaydı Ekleme</p>

<div class="row">
    <div class="col-md-6">
        <form asp-controller="Configuration" asp-action="Insert">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Type"></label>
                <input asp-for="Type" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Value"></label>
                <input asp-for="Value" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="IsActive"></label>
                <input asp-for="IsActive" class="form-control" type="checkbox" />
            </div>
            <div class="form-group">
                <label asp-for="ApplicationName"></label>
                <input asp-for="ApplicationName" class="form-control" />
            </div>
            <button type="submit" class="btn btn-default">Ekle</button>
        </form>
    </div>
</div>

</body>
</html>

Web/Views/Configuration/Edit.cshtml
@model Model.ConfigurationObject

<!DOCTYPE html>

<html>
<head>
    <title>title</title>
</head>
<body>
    <div class="row">
        <div class="col-md-6">
            <form asp-controller="Configuration" asp-action="Update">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <input type="hidden" asp-for="Id" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Type"></label>
                    <input asp-for="Type" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Value"></label>
                    <input asp-for="Value" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="IsActive"></label>
                    <input asp-for="IsActive" class="form-control" type="checkbox" />
                </div>
                <div class="form-group">
                    <label asp-for="ApplicationName"></label>
                    <input asp-for="ApplicationName" class="form-control" />
                </div>
                <button type="submit" class="btn btn-default">Güncelle</button>
            </form>
        </div>
    </div>
</body>
</html>

Web/Views/Configuration/Index.cshtml
@using Model
@model IEnumerable<ConfigurationObject>
@{
    ViewData["Title"] = "Index";
}
<h2>Index</h2>
<p>
    <a asp-action="Create">Yeni Oluştur</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Value)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApplicationName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Value)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsActive)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ApplicationName)
                </td>
                <td>
                    <a href="@Url.Action("Edit", "Configuration",new { id=item.Id})">Güncelle</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Web/Views/Configuration/Success.cshtml
@model object

<!DOCTYPE html>

<html>
<head>
    <title>İşlem Başarılı</title>
</head>
<body>
<div>
    <br/>
    <h3>İşleminiz Başarıyla Gerçekleşti</h3>
    <br/>
    @Html.ActionLink("Anasayfa","Index")
</div>
</body>
</html>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>